// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using VinylRelease.Models;

namespace VinylRelease.Data;

public partial class VinylReleaseContext : DbContext
{
    public VinylReleaseContext(DbContextOptions<VinylReleaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Artist> Artists { get; set; }

    public virtual DbSet<Master> Masters { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Artist>(entity =>
        {
            entity.ToTable("Artist");

            entity.HasIndex(e => e.ArtistName, "IX_Artist_artistName");

            entity.Property(e => e.ArtistId).HasColumnName("artistId");
            entity.Property(e => e.ArtistDesc)
                .IsUnicode(false)
                .HasColumnName("artistDesc");
            entity.Property(e => e.ArtistName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("artistName");

            entity.HasMany(d => d.Masters).WithMany(p => p.Artists)
                .UsingEntity<Dictionary<string, object>>(
                    "ArtistMaster",
                    r => r.HasOne<Master>().WithMany()
                        .HasForeignKey("MasterId")
                        .HasConstraintName("FK_ArtistMaster_masterId"),
                    l => l.HasOne<Artist>().WithMany()
                        .HasForeignKey("ArtistId")
                        .HasConstraintName("FK_ArtistMaster_artistId"),
                    j =>
                    {
                        j.HasKey("ArtistId", "MasterId");
                        j.ToTable("ArtistMaster");
                        j.HasIndex(new[] { "ArtistId" }, "IX_ArtistMaster_artistId");
                        j.HasIndex(new[] { "MasterId" }, "IX_ArtistMaster_masterId");
                    });
        });

        modelBuilder.Entity<Master>(entity =>
        {
            entity.ToTable("Master");

            entity.HasIndex(e => e.MasterName, "IX_Master_masterName");

            entity.Property(e => e.MasterId).HasColumnName("masterId");
            entity.Property(e => e.MasterName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("masterName");
            entity.Property(e => e.MasterYear).HasColumnName("masterYear");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}