// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Build.Framework;
using System;
using System.Collections.Generic;

namespace VinylRelease.Models;

public partial class Artist
{
    public long ArtistId { get; set; }
    
    public string ArtistName { get; set; }

    public string ArtistDesc { get; set; }

    public virtual ICollection<Master> Masters { get; set; } = new List<Master>();
}